### ISSUE TITLE
IndexError: tuple index out of range at cur_repr processing stage

### ISSUE THREAD

**Issue by ENSCMA2** [kmeng01/memit#9]
I'm trying to replicate MEMIT on GPTJ-6B, and I'm getting the following error (just on the first request/prompt example in your memit.ipynb notebook):
```
Traceback (most recent call last):
  File "notebooks/my_new_file_copying_your_interactive_notebook.py", line 58, in <module>
    model_new, orig_weights = demo_model_editing(
  File "/memit/notebooks/experiments/py/demo.py", line 50, in demo_model_editing
    model_new, orig_weights = apply_method(
  File "/memit/notebooks/memit/memit_main.py", line 44, in apply_memit_to_model
    deltas = execute_memit(model, tok, requests, hparams, cache_template=cache_template)
  File "/memit/notebooks/memit/memit_main.py", line 160, in execute_memit
    cur_zs = get_module_input_output_at_words(
  File "/memit/notebooks/memit/compute_z.py", line 212, in get_module_input_output_at_words
    l_input, l_output = repr_tools.get_reprs_at_word_tokens(
  File "/memit/notebooks/rome/repr_tools.py", line 32, in get_reprs_at_word_tokens
    return get_reprs_at_idxs(
  File "/memit/notebooks/rome/repr_tools.py", line 150, in get_reprs_at_idxs
    _process(tr.input, batch_idxs, "in")
  File "/memit/notebooks/rome/repr_tools.py", line 131, in _process
    cur_repr = cur_repr[0] if type(cur_repr) is tuple else cur_repr
IndexError: tuple index out of range
```
I also tried running the non-notebook version via `experiments.evaluate` and got the same exact error. Doing some debugging printouts there revealed that this error occurred on calling `_process` for the input, and the tuple `cur_repr` was an empty tuple, with a `batch_idxs` value of `[[7]]`. Thus, I'm unable to apply MEMIT and move forward with the evaluation. Is anyone else running into this issue, and if so how were you able to resolve it?

**Comment by ENSCMA2** [comment]
Resolved! The issue was that I hadn't installed the right versions of the dependencies (was trying to avoid using setup_conda.sh because it wasn't finding my conda path within a Docker container). Installing the version numbers specified in setup_conda.sh should fix the issue if anyone else has the same problem; thanks to Yunzhi Yao for the tip!
